package:
  name: libmobility
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../../  # Path to your project's source code

build:
  number: 0
  string: cuda{{ CUDA_VERSION }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    
requirements:

  build:
    - cmake >=3.22
    - cuda-version {{ CUDA_VERSION }}
    - gxx
    - cuda-libraries-dev
    - cuda-nvcc 
    - make
    - mkl-devel
    - pybind11
    - python
  run:
    - python
    - cuda-version {{ CUDA_VERSION }}
    - numpy
    - cuda-libraries
    - mkl

test:
  requires:
    - pytest
    - scipy
  imports:
    - libMobility
  source_files:
    - tests
  commands:
    - pytest -vs -k SelfMobility tests/test_*py
    
about:
  home: https://github.com/stochasticHydroTools/libmobility
  license: MIT
  summary: Compute the action of the hydrodynamic mobility (at the RPY/FCM level) of a group of particles (in different geometries) with forces acting on them.
