package:
  name: libmobility
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../../

build:
  number: 0
  string: cuda{{ CUDA_VERSION }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    
requirements:

  build:
    - cmake >=3.22
    - cuda-version {{ CUDA_VERSION }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cuda-libraries-dev
    - cuda-nvcc 
    - make
    - nanobind
    - blas-devel
    - libblas
    - liblapacke
    - nomkl
    - python ={{ PYTHON_VERSION }}
  run:
    - python ={{ PYTHON_VERSION }}
    - cuda-version >={{ CUDA_VERSION }}
    - numpy
    - cuda-cudart
    - libcufft
    - libcublas

test:
  requires:
    - pytest
    - scipy
    # Prove that netlib-linked BLAS works with MKL
    - libblas * *mkl  # [x86 or x86_64]
  imports:
    - libMobility
  source_files:
    - tests
  commands:
    - pytest -vs -k "SelfMobility and not fluct" tests/test_*py
    
about:
  home: https://github.com/stochasticHydroTools/libmobility
  license: MIT
  summary: Compute the action of the hydrodynamic mobility (at the RPY/FCM level) of a group of particles (in different geometries) with forces acting on them.
